FROM ros:noetic-ros-core

RUN apt-get update \
    && apt-get install -y build-essential python3-rosdep cmake \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN rosdep init && rosdep update

# Create ROS workspace
COPY . /ws/src/rospy_message_converter
WORKDIR /ws

# Install the package and its dependencies
RUN rosdep install --from-paths src --ignore-src --rosdistro noetic -y

# Set up the development environment
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    catkin_make install"
